MAKE = Makefile

FIRST_HALF_OF_YEAR_DIR = 前期
LATTER_HALF_OF_YEAR_DIR = 後期

F_HOMEWORK = $(FIRST_HALF_OF_YEAR_DIR)/課題
L_HOMEWORK = $(LATTER_HALF_OF_YEAR_DIR)/課題

F_PRACTICE = $(FIRST_HALF_OF_YEAR_DIR)/練習
L_PRACTICE = $(LATTER_HALF_OF_YEAR_DIR)/演習

F_SHORT_TEST1 = $(FIRST_HALF_OF_YEAR_DIR)/小テスト1

F_H_1 = $(F_HOMEWORK)/課題1/$(MAKE)
F_H_2 = $(F_HOMEWORK)/課題2/$(MAKE)
F_H_3 = $(F_HOMEWORK)/課題3/$(MAKE)
F_H_4 = $(F_HOMEWORK)/課題4/$(MAKE)
F_H_5 = $(F_HOMEWORK)/課題5/$(MAKE)

